# Generated by Django 5.2.8 on 2025-11-29 23:32

import django.db.models.deletion
import processor.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to=processor.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('grayscale', 'Escala de Cinza'), ('brightness', 'Brilho'), ('contrast', 'Contraste'), ('sharpness', 'Nitidez'), ('blur', 'Desfoque')], max_length=20)),
                ('value', models.FloatField(help_text='Valor do parâmetro aplicado')),
                ('processed_image', models.ImageField(upload_to='processed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processor.imagesession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
