# Generated by Django 5.2.8 on 2025-11-30 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesession',
            name='adjustments',
            field=models.JSONField(default=dict, help_text='Current adjustment values'),
        ),
        migrations.CreateModel(
            name='ProcessingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustments', models.JSONField(help_text='Adjustment values at snapshot time')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='processor.imagesession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProcessingStep',
        ),
    ]
